### ISSUE TITLE
put real timestamp in PCAP packet header

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/argus#11]
so it displays right on Wireshark

**Comment by keomabrun** [comment]
From BeamLogic documentation:
> Timestamp: an integer value representing the timestamp at which the packet started to be
received (expressed in units of 1/3 microseconds). The timestamp represents the value of
an internal 48-bit free-running timer with a frequency of 3 MHz

**Comment by keomabrun** [comment]
The official ZEP `timestamp` field is an NTP format timestamp while the BeamLogic returns third of microseconds.
I think we should use the `Reserved` field to put the Beamlogic timestamp (and RSSI).

This is what the IoT-Lab does: https://github.com/iot-lab/iot-lab/wiki/Control-Node-Sniffer#zepv2-format

**Comment by twatteyne** [comment]
+1
