### ISSUE TITLE
Incorrect frame length indicated in ZEP header. 

### ISSUE THREAD

**Issue by changtengfei** [openwsn-berkeley/argus#16]
With the wireshark opened through argus, I always get a frame length of ieee802.15.4 packet +1.
E.g. if the frame length is 49, in zep header it indicates 50. This result errors for dissecting the last bytes of ieee802.15.4 frame. I don't have this issue when I sniff the same frame through my sniffer (TI/openmote sniffer). 

I investigate the code of argus and suspect this is on the server side:
checkout the code starting from following line, (check the index offset used in the frame list)
https://github.com/openwsn-berkeley/argus/blob/master/ArgusProbe_Beamlogic.py#L159

It may include the LENGTH field of IEEE802.15.4 frame when calculating the frame length, which shouldn't. Just guess since I don't have the access of the machine is running the script, can't verify for now.

**Comment by sieben** [comment]
@twatteyne what do you think about it?

**Comment by twatteyne** [comment]
@changtengfei, your explanation makes sense, although I haven't verified. I suggest you fix it locally on the machine with the server, verify your fix actually fixes the issue, and submit a PR for @sieben to integrate

**Comment by keomabrun** [comment]
Some related details:
https://github.com/openwsn-berkeley/argus/issues/24
