### ISSUE TITLE
PAN ID compression bit is fixed.

### ISSUE THREAD

**Issue by changtengfei** [openwsn-berkeley/argus#22]
Any reason why we want to fix the PANID compression?
https://github.com/openwsn-berkeley/argus/blob/master/ArgusProbe_Beamlogic.py#L161

**Comment by changtengfei** [comment]
@twatteyne I guess you made this changes for testing and forgot to remove?

**Comment by twatteyne** [comment]
very possibly!

**Comment by changtengfei** [comment]
I checked the standard and for the case that if src and dest address are presented as extend address and PANID is presented, the PAN ID compression should be set to zero. 
I will reverse this changes. Thanks for the quick response!

**Comment by changtengfei** [comment]
Fixed.
